/**
* Recipe Puppy
* Recipe Puppy
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Recipe

import com.squareup.moshi.Json

/**
 * 
 * @param title 
 * @param results 
 */

data class RecipeList (
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "results")
    val results: kotlin.collections.List<Recipe>? = null
)

